services:
  gym-tracker:
    build:
      context: .
      args:
        VITE_BASE_PATH: /
        VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
    restart: unless-stopped
    ports:
      - "3003:80"
